name: Create Pull Request
run-name: ${{ github.actor }} is creating a pull request

on:
  push:
    branches:
      - "feature/**"

env:
  ISSUE_ID: "${{ github.ref_name }}"
  LATEST_RELEASE_BRANCH: ${{ env.latest_branch_name }}

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find Latest Release Branch
        run: |
          git fetch
          echo "latest_branch_name=$(git branch -a | grep -E -o 'release/[0-9]*' | sort -r | head -1 | tr -d ' ')" >> $GITHUB_ENV
          echo "$LATEST_RELEASE_BRANCH"
          echo "$ISSUE_ID"
