name: Create Pull Request
run-name: ${{ github.actor }} is creating a pull request

on:
  push:
    branches:
      - "feature/**"

env:
  ISSUE_ID: "${{ github.ref_name }}"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch

      - name: Find Latest Release Branch
      - run: echo "::set-output name=LATEST_RELEASE_BRANCH::$(git branch -a | grep -E -o 'release/[0-9]*' | sort -r | head -1 | tr -d ' ')"
      - run: echo "$ISSUE_ID"
