name: Create Pull Request
run-name: ${{ github.actor }} is creating a pull request

on:
  push:
    branches:
      - "feature/**"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          git fetch
          echo "latest_branch_name=$(git branch -a | grep -E -o 'release/[0-9]*' | sort -r | head -1 | tr -d ' ')" >> $GITHUB_ENV
          echo "issue_id=$(echo '${{ github.ref_name }}' | cut -d '/' -f 2-)" >> $GITHUB_ENV

      - name: Check Latest Release Branch
        if: env.latest_branch_name == null
        run: |
          echo "::error::There is no release branch to request."
          exit 1

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ env.latest_branch_name }}
          pr_title: "[${{ env.issue_id }}] Automatic Generated Draft PR"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_assignee: ${{ github.actor }}
          pr_draft: true
