name: Create Pull Request
run-name: ${{ github.actor }} is creating a pull request

on:
  push:
    branches:
      - "feature/**"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find Latest Release Branch
        run: |
          git fetch
          echo "latest_branch_name=$(git branch -a | grep -E -o 'release/[0-9]*' | sort -r | head -1 | tr -d ' ')" >> $GITHUB_ENV

      - name: Check Latest Release Branch
        if: env.latest_branch_name == null
        run: |
          echo "Error: There is no release branch to request."
          exit 1
