name: Auto-Create PR
run-name: Automatically creating a PR for ${{ github.actor }}

on: create

jobs:
  create-feature-pull-request:
    if: ${{ startsWith(github.ref_name, 'feature/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          git fetch
          echo "issue_id=$(echo '${{ github.ref_name }}' | cut -d '/' -f 2)" >> $GITHUB_ENV
          echo "latest_release_branch=$(git branch -a | grep -E -o 'release/[0-9]*' | sort -r | head -1 | tr -d ' ')" >> $GITHUB_ENV

      - name: Check latest release branch exists
        if: env.latest_release_branch == null
        run: |
          echo "::error::There is no release branch to request."
          exit 1

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ env.latest_release_branch }}
          pr_title: "[${{ env.issue_id }}] Automatically Created Feature PR"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_assignee: ${{ github.actor }}
          pr_draft: true

  create-hotfix-pull-request:
    if: ${{ startsWith(github.ref_name, 'hotfix/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "issue_id=$(echo '${{ github.ref_name }}' | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "[hotfix][${{ env.issue_id }}] Automatically Created Hotfix PR"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_assignee: ${{ github.actor }}
          pr_draft: true
