name: Create Pull Request
run-name: ${{ github.actor }} is creating a pull request

on:
  push:
    branches:
      - "feature/**"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
