name: PR Approval Reminder

on:
  schedule:
    - cron: '0 10 * * 1-5'  # 매일 10시에 실행
  workflow_dispatch:

jobs:
  pr-approval-reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: 설정 및 종속성 설치
      run: |
        npm install -g github
        npm install -g @actions/core
      shell: bash

    - name: PR 목록 가져오기
      id: get-prs
      run: |
        PR_LIST=$(gh pr list --json number,title,url,requested_reviewers -s "open" -q "is:pr review:changes-requested" | jq -r '.[] | select(.requested_reviewers | length > 1) | .number, .title, .url' | paste -sd " " -)
        echo "::set-output name=pr_list::$PR_LIST"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: PR 목록을 Slack 알림으로 전송
      if: ${{ steps.get-prs.outputs.pr_list != '' }}
      uses: rtCamp/action-slack-notify@v2.2.1
      with:
        status: ${{ job.status }}
        text: "${{ steps.get-prs.outputs.pr_list }}"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
