name: PR Approval Reminder

on:
  schedule:
    - cron: '0 10 * * 1-5'  # 평일 10시에 실행
  workflow_dispatch: # 임의로 실행

jobs:
  pr-approval-reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 설정 및 종속성 설치
      run: |
        npm install -g github
        npm install -g @actions/core
      shell: bash

    - name: PR 목록 가져오기
      id: get-prs
      run: |
        PR_LIST=$(gh pr list --state=open --draft=false --json number,title,url,state,reviews -q ".[] | {number,title,url,state,reviews}")
        echo "$PR_LIST"
        echo "::set-output name=pr_list::$(echo "$PR_LIST")"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
