name: PR Approval Reminder

on:
  schedule:
    - cron: '0 10 * * 1-5'  # 평일 10시에 실행
  workflow_dispatch: # 임의로 실행

jobs:
  pr-approval-reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 설정 및 종속성 설치
      run: |
        npm install -g github
        npm install -g @actions/core
      shell: bash

    - name: PR 목록 가져오기
      id: get-prs
      run: |
        printf "%s\n" "오픈된 PR의 목록 불러오기"
        PR_LIST=$(gh pr list --state=open --draft=false --json number,title,url,reviews -q ".[] | {number,title,url,reviews}")
        printf "%s\n" "$PR_LIST"

        printf "%s\n"  "승인된 리뷰 개수가 2개 미만인 PR 목록 만들기"
        TARGET_PR_URL_LIST=""
        echo "$PR_LIST" | while read -r line; do
            url=$(echo "$line" | jq -r '.url')
            approved_reviews=$(echo "$line" | jq -r '.reviews | map(select(.state == "APPROVED")) | length')
            if [ "$approved_reviews" -lt 2 ]; then
                printf "%s\n" "- $TARGET_PR_URL_LIST"
                TARGET_PR_URL_LIST+="\n$url"
                printf "%s\n" "+ $TARGET_PR_URL_LIST"
            fi
        done
        echo "PRs with less than 2 approvals: $TARGET_PR_URL_LIST" > slack_message.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send Slack Notification
      uses: rtCamp/action-slack-notify@v2.2.1
      with:
        slack-channel: "서비스개발_fe_hogangnono"
        slack-username: GitHub Actions
        slack-text-file: slack_message.txt
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

