name: PR Approval Reminder

on:
  schedule:
    - cron: '0 10 * * 1-5'  # 평일 10시에 실행
  workflow_dispatch: # 임의로 실행

jobs:
  pr-approval-reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 설정 및 종속성 설치
      run: |
        npm install -g github
        npm install -g @actions/core
      shell: bash

    - name: PR 목록 가져오기
      id: get-prs
      run: |
        PR_LIST=$(gh pr list --state=open --draft=false --json number,title,url,reviews -q ".[] | {number,title,url,reviews}")
        echo "$PR_LIST"

        PR_LIST_NEED_REVIEW=""
        
        echo "$PR_LIST" | while read -r line; do
            # PR의 state, number, title, url, reviews 정보 추출
            state=$(echo "$line" | jq -r '.state')
            number=$(echo "$line" | jq -r '.number')
            title=$(echo "$line" | jq -r '.title')
            url=$(echo "$line" | jq -r '.url')
            reviews=$(echo "$line" | jq -r '.reviews | length')
        
            # state가 "OPEN"이고, reviews 개수가 2 미만인 경우만 PR_LIST_NEED_REVIEW에 추가
            if [ "$reviews" -lt 2 ]; then
                PR_LIST_NEED_REVIEW+="\n{\"number\":$number,\"title\":\"$title\",\"url\":\"$url\",\"state\":\"$state\",\"reviews\":$reviews}"
            fi
        done
        
        # 결과 출력
        echo -e "$PR_LIST_NEED_REVIEW"
        
        echo "::set-output name=pr_list::$(echo "$PR_LIST")"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
